[package]
name = "p49"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permute = "0.1.0"
itertools = "0.10.2"
primes = { path = "../lib/primes" }
digits = { path = "../lib/digits" }

