[package]
name = "p77"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.2.1"
primal = "0.3.0"
once_cell = "1.9.0"